### ISSUE TITLE
List of available Test Ski versions is not updated

### ISSUE THREAD

**Issue by deepiksdev** [librelioniv2/ios-testmatos#11]
cc @avittecoqDAJ

**Comment by deepiksdev** [comment]
After uncommenting https://github.com/librelioniv2/ios-testmatos/blob/master/Classes/WADocumentDownloader.m#L549 , got the following message in log

`2015-09-14 14:35:00.494 ScriptTempProductName[25302:1743203] will launch connection for http://librelio-europe.s3.amazonaws.com/numero/ipad/Magazines.plist with connexion <NSURLConnection: 0x7be13300> { request: <NSMutableURLRequest: 0x7be15060> { URL: http://librelio-europe.s3.amazonaws.com/numero/ipad/Magazines.plist } } in Downloader <WADocumentDownloader: 0x7be19b60>`

For some reason, instead of trying to download `http://librelio-europe.s3.amazonaws.com/niveales/testskis2014/Magazines.plist`the app tries to download `http://librelio-europe.s3.amazonaws.com/numero/ipad/Magazines.plist`. We need to understand why.

**Comment by deepiksdev** [comment]
There seems to be something wrong with the script: in the regular iOS project, the `Application.plist`file in the `ScriptTarget`folder is updated during the build process: it is replaced by the one in the Dropbox folder. In this project, `Application.plist` is not updated.

**Comment by deepiksdev** [comment]
I double checked, the problem is really related to the project, not to `path.txt`or the folder in Dropbox: when building the app from the regular iOS project, the `Application.plist`file is updated.

**Comment by deepiksdev** [comment]
Tried adding the following code in different locations in `script.sh`, but found that `Application.plist`is updated before the script is run. 

```
CFBUNDLEVERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" $HOME/Documents/Dev/ios/ScriptTarget/Application.plist)
echo "$CFBUNDLEVERSION"
```

**Comment by avittecoqDAJ** [comment]
Hi,

I change the path.txt with the new values of the dropbox and changed some values in the Application.plist and to me it seems to work properly.
I do have the two release of the magazine 2014 and 2015 which are the only two available on the S3.
Is that what we are supposed to have ?

**Comment by deepiksdev** [comment]
@avittecoqDAJ 

> I change the path.txt with the new values of the dropbox and changed some values in the Application.plist and to me it seems to work properly.
> You should not need to update `Application.plist`, it should be updated automatically. But congrats for having this work.
> 
> I do have the two release of the magazine 2014 and 2015 which are the only two available on the S3.
> Is that what we are supposed to have ?

These are not exactly magazines but rather yearly versions of the tests. We should test the 2016 version which was recently uploaded by @librelioniv. See issue #13 .

**Comment by deepiksdev** [comment]
For the time being, in order to avoid losing time, as suggested by @avittecoqDAJ, we'll copy `Application.plist`manually to the `ScriptTarget` folder.
